### ISSUE TITLE
KLAS 웹사이트 구조 변경으로 인한 오류 수정

### ISSUE THREAD

**Issue by mirusu400** [klas-helper/klas-helper-extension#16]
현재 KLAS 사이트가 수정되면서 일부 사이트 구조 및 함수가 수정되었고, 이로인해 작동하지 않는 기능이 있습니다.

밑은 현재까지 확인된 내역들이며, 차차 수정될 예정입니다.

- [x] 자동 세션 갱신 미작동 오류 - 현재 일부 브라우저에서 오류가 있는듯 합니다
- [x] 2분 쿨타임 제거 미작동 오류
- [x] 수강인원 조회 기능 미작동 오류
- [x] 인증 우회 미작동 오류 - 현재 [인증 우회] 버튼으로 Legacy를 남긴 상태입니다
- [x] 영상 다운로드 버튼 미 렌더링 오류

**Comment by mirusu400** [comment]
`std/lis/evltn/OnlineCntntsStdPage.do` 경로에서 2분 쿨타임 제거가 여전히 동작안하고 있어서 나중에 수정이 필요해보입니다

**Comment by nbsp1221** [comment]
해당 페이지의 소스코드를 확인해 봤는데

```js
var count = 0;
var interval = setInterval(function() {
	$("#btn-cooltime").remove();
	$("#btn-cooltime").unbind('click').click();
	count++;	
	if (count == 60) {
		clearInterval(interval);
	}
}, 1000);
```

의도적으로 KLAS Helper를 무력화하기 위한 코드가 보이는 것 같네요. 뚫을려면 뚫을 수야 있을 것 같은데.. 학교 관계자분들이 무력화하려고 시도하는 것으로 봐서는 뚫어도 앞으로 다시 막힐 가능성이 높을 것 같아요. 일단 작업은 해두겠습니다.

**Comment by mirusu400** [comment]
마찬가지로 자동 세션 갱신도 계속해서 호출하는 함수명을 수정함으로써 확장프로그램의 동작을 무력화할려고 하고 있네요

https://github.com/klas-helper/klas-helper-extension/commit/b8aa69448a7b4a75d3a272f336759c5ac29ea005

위 커밋에서 간단하게 수정하긴 했지만, 계속 모니터링해서 수정할 필요가 있어 보입니다

**Comment by mirusu400** [comment]
![image](https://user-images.githubusercontent.com/25397908/235294795-91bcdec7-1676-46f8-98e1-8643b9423a1c.png)


현재 지금까지의 커밋을 이용해 `2.0.2.2` 버전을 릴리즈하였는데, 해당 버전을 통해 인증 우회를 했을 때 일부 사용자들이 위와 같은 오류를 겪고 있습니다

그 외에도 헬퍼 업데이트에 맞춰서 `영상 다운로드` 렌더링을 숨기도록 페이지 구조를 변경하였는데 이 점도 수정이 필요해 보입니다.

**Comment by nbsp1221** [comment]
2분 쿨타임이나 인증이 적용되는 강의가 특정 강의(새롭게 올라온 강의)에만 적용되고 있는 것 같습니다. 저에겐 지금 새로운 강의가 없어서 이슈 재현이 어려운 상황이라 당장 해결하기에는 힘들 것 같습니다. ㅠ

추가적으로 현재 로직이 기존의 로직을 헬퍼로 강제로 덮어씌워서 동작하는 방식인데, 만약 헬퍼에 문제가 생기면 헬퍼를 꺼야만 학교 사이트를 이용할 수 있는 상황이라서 개선이 필요해 보입니다.

![image](https://user-images.githubusercontent.com/50603255/235338862-6a26f146-a042-4b65-8db4-349036c71c80.png)

이런 느낌으로 버튼을 따로 추가해서 평상시에는 `헬퍼 보기` 버튼을 이용하다가 만약 문제가 생기면 헬퍼를 따로 종료할 필요 없이, 기존의 `보기` 버튼으로 언제든지 기존 로직을 이용할 수 있는 방법 등을 생각해보고 있습니다.

**Comment by mirusu400** [comment]
저도 현재 막힌 이후 올라온 강의가 하나도 없어서 분석이 힘드네요 ㅠㅠ

당장 막는용도론 괜찮겠지만 장기적으로 보면 이런 상황을 모르는 새로운 유저분들이 혼란을 겪을수도 있을거같아서, 임시적으로 구현한뒤에 나중에 개선방안을 생각해보는게 좋아보입니다

**Comment by nbsp1221** [comment]
https://github.com/klas-helper/klas-helper-extension/commit/d51b5bf907fcf454f22ca8ae6b145457c5f871b2

해당 커밋에서 만약 문제가 있더라도 KLAS Helper는 사용할 수 있도록 인증 우회 기능을 버튼으로 따로 적용할 수 있도록 변경했습니다.

**Comment by mirusu400** [comment]
@nbsp1221 
정보처 측의 요청으로 일부 기능을 삭제할 예정입니다. 삭제하는 기능은 아래와 같습니다

* 동영상, 강의 슬라이드 다운로드 기능
* 스마트인증 기능

**Comment by nbsp1221** [comment]
@mirusu400 확인했습니다
