### ISSUE TITLE
강의계획서와 에브리타임 강의실 연동

### ISSUE THREAD

**Issue by nbsp1221** [klas-helper/klas-helper-extension#20]
강의계획서에서 강의를 검색할 때 에브리타임 강의실에 있는 별점, 과제, 조모임, 성적 같은 정보를 같이 연동해서 보여주는 기능, 그리고 따로 버튼을 누르면 에브리타임 강의실 페이지로 바로 이동할 수 있는 기능을 만들면 좋을 것 같습니다.

이를 구현하기 위해서는 에브리타임 강의실 정보를 미리 크롤링해서 JSON 같은 형태의 파일로 담아둔 뒤 확장 프로그램 소스코드에 포함시켜 같이 배포하는 방법이 생각나네요.

혹시 다른 의견이 있다면 댓글 부탁드립니다.

**Comment by mirusu400** [comment]
아이디어 자체는 좋지만, 에타가 서드파티 접근 자체에 민감해서 연동해서 보여주는건 좀 어렵지 않을까요?

일전에 지인이 에타 크롤링 잠깐 했다가 그대로 3달인가 1년 정지 먹었던걸로 기억해서요

단순히 에타 강의평으로 넘어가는 바로가기를 만드는 것 정도는 괜찮아 보이는데, 이것도 결국 에타 강의평 링크를 수집해야되서 쉽지만은 않아보입니다

**Comment by nbsp1221** [comment]
넵, 안 그래도 데이터 수집 부분을 고민해보고 있었는데 프로그램이나 셀레니움으로 만들어서 크롤링 하는 것은 캡챠도 생겼고 잘못하면 정지될 수도 있어서 어려울 것 같습니다. 그렇다고 수작업하는 것도 거의 불가능에 가깝고요.

그래서 생각해 본 방법이 크롬 브라우저에서 에타에 접속한 뒤에는 개발자 도구로 자바스크립트 기능을 사용할 수 있으니까 이를 이용해서 스크립트를 만들어 데이터를 수집하는 것 정도는 가능하지 않을까 싶습니다. 수집된 데이터를 저희 헬퍼에 하드코딩하고 제공해주는 방법이죠.

실시간으로 연동되면 더욱 좋겠지만 이건 거의 불가능하다고 봐야 하고... 학기가 시작하기 전에 한 번씩 업데이트해주는 방식으로 가면 괜찮지 않을까요? 강의평이 자주 바뀌는 것도 아니긴 하고요.

문제가 없다면 제가 한번 작업해 보겠습니다.

**Comment by mirusu400** [comment]
자바스크립트로 이미 렌더링 된 데이터만 긁어온다면 문제가 없어보입니다

(다만 에타 크롤링 기능을 헬퍼에 넣으면 문제가 생길것 같네요)

우선 올려주신 #19 PR 확인하고 나서 천천히 작업 해보면 좋을것같습니다
