### ISSUE TITLE
Safari 지원하기

### ISSUE THREAD

**Issue by heoblitz** [klas-helper/klas-helper-extension#4]
<img width="1440" alt="스크린샷 2021-12-06 오전 12 20 50" src="https://user-images.githubusercontent.com/25315898/144752636-d3e08aff-9860-4448-a402-bc6d92a14bb5.png">

Chrome Extension -> Safari Extension 으로 변환하니 대체로 잘 동작하는 것 같습니다.
다만 Safari 에서 지원하는 API 가 달라서 부분적으로 코드를 변경하는 작업과 기능 버그를 해결해야할 것 같습니다. 
( 홈 수강과목은 작동 X )

Safari Extension 관련해서 작업이 가능할 것 같은데요. ( 추후에는 iOS, iPadOS 까지 )
Chrome Extension 과 다르게 프로젝트 구조, 배포 방법이 달라서 별도로 레포를 만들고 앱스토어에 개인 계정으로 배포해야할 것 같습니다. 혹시 어떤 방법으로 진행하면 더 좋을지 의견 남겨주시면 감사하겠습니다. 

아직 맥이나 아이폰 적용 계획이 없으시다면 편하게 말씀해주시면 좋을 것 같습니다. 👍

**Comment by mirusu400** [comment]
안녕하세요!

제 프로필을 보면 아시겠지만, 지금 당장 사파리 익스텐션을 개발할수 있는 환경이 안됩니다 (당장 Xcode가 필요한데, 전 군대에 있으니까요). 나중에 저도 전역 후 맥북을 사면 사파리 익스텐션도 손을 대볼려고 했는데, 벌써 도움을 주시는 분이 있네요. 감사합니다.

---
각설하고, 현재 클라스 헬퍼 플러그인은 이런 규칙으로 개발을 하고 있습니다.
* 단순히 `KLAS`에서 데이터를 가져와 렌더링, DOM조작만 하는 경우 [기존 유저스크립트](https://github.com/klas-helper/klas-helper) 에 개발
* 그 외 캐시나 저장 기능, CORS 기능이 필요한것은 [확장 프로그램](https://github.com/klas-helper/klas-helper-extension)에 개발 

만약 Safari Extension 버전도 추가를 한다면, 기존 유저스크립트는 그렇다 쳐도 확장 프로그램 때문에 두 번 개발을 해야될 가능성도 있는데, 이쪽에 대해선 좀 더 생각을 해볼 필요가 있어 보입니다.  

* 만약 제가 만든 코드들에 +α 하는거라면, `Github Actions`나 `Submodule` 같은 Git, Github 내의 기능으로 충분히 가능해보이고
* 아니라면, 매 업데이트가 나올때마다 만드신 레포에 제가 꾸준히 이슈나 풀리퀘를 날리는수밖에.. 없네요

후자의 방법은 확실히 깔끔하지 못한 방법이라고 생각합니다. 혹시 뾰족한 방법이나 방법이 있으시다면 의견 부탁드리겠습니다!

**Comment by heoblitz** [comment]
별도로 Safari 레포를 만들어서 Git Submodule 로 관리하는 방법이 가장 좋을 것 같습니다 :) 업데이트 나올때마다 반영해서 배포하는 방식이 좋아보이네요. 스크립트 하나로도 가능할 것 같은데, 앱스토어 버전이나 배포 인증 관련 부분도 있어서 레포가 따로 있으면 작업이 편할 것 같습니다.

확인해보니 Safari Extension 는 다크모드, 동영상 다운로드 기능, 아래 이슈 제외하고 잘 작동하는 것 같습니다.

가장 큰 이슈는 홈 수강 과목 현황이 로드 안되는 현상인데, Safari Date 쪽 이슈인 것 같습니다. 
[관련 게시글](https://velog.io/@yeoj1n/safari-%EC%97%90%EC%84%9C-new-Date-%EC%82%AC%EC%9A%A9%EC%8B%9C-Invalid-Date-%ED%98%84%EC%83%81)

요건 나중에 분기처리나 Chrome 에서도 정상적으로 동작하는 코드로 수정해서 klas-helper 쪽에 PR 하겠습니다.
자세한 답변 감사합니다.
