### ISSUE TITLE
메니페스트 V2 지원 종료 관련 이슈

### ISSUE THREAD

**Issue by jwmsg0525** [klas-helper/klas-helper-extension#5]
안녕하세요, Klas Plugin 을 개발했던 개발자 입니다.
2022년 1월부터 새로운 크롬 스토어에 올라가는 extension 솔루션에 대하여 Manifest V2를 지원 종료하고 Manifest V3만 허용하겠다는 메일을 수신받았습니다.
V2로 기존에 업로드된 확장프로그램에 대해 당분간은 V2 를 계속 지원할 예정이라고 밝혔으나,
V3로 마이그레이션 하는것을 추천한다는 지침이 있었습니다.
이에 확인 바랍니다!

**Comment by jwmsg0525** [comment]
https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/

**Comment by mirusu400** [comment]
음 수정하고있는데 원격 eval 코드를 가져오는 부분이 자꾸 걸리네요

https://github.com/klas-helper/klas-helper-extension/blob/1ec0d48567adebedee410dedfd07af43a129a594/content.js#L65-L94

이부분에서 `document.head.appendChild(scriptElement);` 로 klas-helper (베타 버전)원격 코드를 가져오는데 csp에 걸려서 문제가 나네요. 다른 예제들 찾아보니 다 v2라서 적용하기가 어렵네요.. 우선 급한건 아닌거 같으니 조금 뒤로 미뤄놔야 될 듯 합니다.

**Comment by jwmsg0525** [comment]
저도 관련된 자료 찾아서 함께 커밋 해 두겠습니다 :)

**Comment by Tianea2160** [comment]
이미 아실 수도 있는데 도움이 될까 싶어서 글을 씁니다.
이전에 사용하시던 버전 mv2 코드중에서 chrome.browserAction 기능은 mv2까지만 사용가능하다고 합니다.

~~~
chrome.runtime.onMessage.addListener(function (msg, sender, sendResponse) {
    if (msg.action === "updateIcon") {
        if (msg.value === "disabled") {
            chrome.action.setIcon({
                path: {"32": "./icon/off.png"}
            });
        } else {
            chrome.action.setIcon({
                path:{"48": "./icon/on.png"}
            });
        }
        sendResponse("change icon is success");
    }
});
~~~
버전을 올리시면서 도움이 되셨으면 좋겠습니다.
